<a href="https://colab.research.google.com/github/mansiKhule2331/Python/blob/main/Assigment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#import numpy module with alias np
import numpy as np

In [5]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it
arr = np.array([1, 2, 3])

In [6]:
# print output
print(arr)

[1 2 3]


In [7]:
# print output
print(arr)

[1 2 3]


In [12]:
#define a,b,c and d as instructed above

a = np.array(10)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [13]:
#print dimentions of a,b, c and d
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
# print shape of each a,b ,c and d
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(3,)
(2, 3)
(2, 2, 3)


In [15]:
# print data type of c and d
print(c.dtype)
print(d.dtype)

int64
int64


In [16]:
#print type of a and b variable
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [17]:
# Lets check length of array b, using len() function
print(len(b))

3


In [18]:
# Define l1,l2,l3 and l4 as stated above.
l1 = [10, 20, 30]
l2 = [40, 50, 60]
l3 = np.array(l1)
l4 = np.array(l2)

In [19]:
#code here as instructed above
%timeit [i*j for i, j in zip(l1, l2)]

668 ns ± 194 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [20]:
# Multiply l3 and l4
%timeit l3 * l4

571 ns ± 9.97 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [21]:
#Create a numpy array using arange with 1 and 11 as parameter in it
arr1 = np.arange(1, 11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [22]:
# Create an array using arange passing 1,11 and 2 as parameter in iter
arr2 = np.arange(1, 11, 2)
print(arr2)

[1 3 5 7 9]


In [23]:
# create numpy array using eye function with 3 as passed parameter
eye_arr = np.eye(3)
print(eye_arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# Using arange() to generate numpy array x with numbers between 1 to 16
x = np.arange(1, 17)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [25]:
# Reshape x with 2 rows and 8 columns
x2 = x.reshape(2, 8)
print(x2)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [26]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:
x3 = x.reshape(2, 4, 2)
print(x3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [27]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4
x4 = x.reshape(4, -1)
print(x4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [28]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
y = x.reshape(2, 4, -1)
print(y)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [29]:
# Flattening y
print(y.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [30]:
# Create an array a with all even numbers between 1 to 17
a = np.arange(2, 18, 2)
print(a)

[ 2  4  6  8 10 12 14 16]


In [31]:
# Get third element in array a
print(a[2])

6


In [32]:
#Print 3rd, 5th, and 7th element in array a
print(a[2], a[4], a[6])

6 10 14


In [34]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [35]:
# print the 3rd element from the 3rd row of a
print(a[2,2])

9


In [36]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [37]:
# Print 3rd element from 2nd list which is 1st list in nested list passed.
print(b[0,1,2])

6


In [38]:
# Create 1D array
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
# Slice elements from 1st to 5th element from the following array:
print(arr[1:5])

[1 2 3 4]


In [40]:
# Slice elements from index 5 to the end of the array:
print(arr[5:])

[5 6 7 8 9]


In [41]:
# Slice elements from the beginning to index 5 (not included):
print(arr[:5])

[0 1 2 3 4]


In [42]:
# Print every other element from index 1 to index 7:
print(arr[1:7:2])

[1 3 5]


In [43]:
# Return every other element from the entire array arr:
print(arr[::2])

[0 2 4 6 8]


In [44]:
# Print array a
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'
print(a[2,1:5])

In [46]:
# In array 'a' print index 2 from all the elements :
print(a[:,2])

[3 6 9]


In [47]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:
print(a[:,1:])

[[2 3]
 [5 6]
 [8 9]]


In [48]:
# x1=
x1 = np.array([1, 2, 3, 4, 5])

In [49]:
# assign x2 = x1
x2 = x1

In [50]:
#print x1 and x2
print(x1)
print(x2)

[1 2 3 4 5]
[1 2 3 4 5]


In [51]:
# change 1st element of x2 as 10
x2[0] = 10

In [52]:
#Again print x1 and x2
print(x1)
print(x2)

[10  2  3  4  5]
[10  2  3  4  5]


In [53]:
# Check memory share between x1 and x2
print(np.shares_memory(x1, x2))

True


In [54]:
# Create a view of x1 and store it in x3.
x3 = x1.view()

In [55]:
# Again check memory share between x1 and x3
print(np.shares_memory(x1, x3))

True


In [56]:
#Change 1st element of x3=100
x3[0] = 100

In [57]:
#print x1 and x3 to check if changes reflected in both
print(x1)
print(x3)

[100   2   3   4   5]
[100   2   3   4   5]


In [58]:
# Now create an array x4 which is copy of x1
x4 = x1.copy()

In [59]:
# Change the last element of x4 as 900
x4[-1] = 900

In [60]:
# print both x1 and x4 to check if changes reflected in both
print(x1)
print(x4)

[100   2   3   4   5]
[100   2   3   4 900]


In [61]:
#Check memory share between x1 and x4
print(np.shares_memory(x1, x4))

False


In [62]:
# stack x1 and x4 along columns.
print(np.column_stack((x1, x4)))

[[100 100]
 [  2   2]
 [  3   3]
 [  4   4]
 [  5 900]]


In [63]:
#stack x1 and x4 along rows
print(np.row_stack((x1, x4)))

[[100   2   3   4   5]
 [100   2   3   4 900]]


<ipython-input-63-1679587533>:2: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((x1, x4)))


In [64]:
# arr1 =
arr1 = np.array([1,2,3])
# arr2 =
arr2 = np.array([4,5,6])
##join arr1 and arr2 along rows using concatenate() function
print(np.concatenate((arr1, arr2)))

[1 2 3 4 5 6]


In [65]:
##join arr1 and arr2 along columns using concatenate() function
print(np.concatenate(([arr1], [arr2]), axis=0))

[[1 2 3]
 [4 5 6]]


In [66]:
# append arr2 to arr1
print(np.append(arr1, arr2))

[1 2 3 4 5 6]


In [67]:
# Inserts values into array x1 before index 4 with elements of x4
print(np.insert(x1, 4, x4))

[100   2   3   4 100   2   3   4 900   5]


In [68]:
# delete 2nd element from array x2
print(np.delete(x2, 2))

[100   2   4   5]
